version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./vhost:/etc/nginx/conf.d/vhost
      - ./ssl:/etc/nginx/ssl
      - ./html:/usr/share/nginx/html
    network_mode: host
    restart: always
